GET http://localhost:3003/api/players

###
GET http://localhost:3003/api/players?long_name=damian+alfredo+varayud

###
GET http://localhost:3003/api/players?limit=2&long_name=Lionel+Andrés+Messi+Cuccittini

###
GET http://localhost:3003/api/players/143164

###
POST http://localhost:3003/api/players
Content-Type: application/json

{
  "fifa_version": "23",
  "fifa_update": "1",
  "player_face_url": "https://cdn.sofifa.net/players/202/811/23_120.png",
  "long_name": "Damian Alfredo Varayud",
  "player_positions": "GK",
  "club_name": "Aston Villa",
  "nationality_name": "Argentina",
  "overall": 84,
  "potential": 84,
  "value_eur": 29000000,
  "wage_eur": 95000,
  "age": 34,
  "height_cm": 180,
  "weight_kg": 100,
  "preferred_foot": "Right",
  "weak_foot": 4,
  "skill_moves": 1,
  "international_reputation": 3,
  "work_rate": "Medium/Medium",
  "body_type": "Stocky (185+)",
  "pace": 0,
  "shooting": 0,
  "passing": 0,
  "dribbling": 0,
  "defending": 0,
  "physic": 0,
  "attacking_crossing": 22,
  "attacking_finishing": 16,
  "attacking_heading_accuracy": 26,
  "attacking_short_passing": 50,
  "attacking_volleys": 13,
  "skill_dribbling": 13,
  "skill_curve": 22,
  "skill_fk_accuracy": 20,
  "skill_long_passing": 59,
  "skill_ball_control": 35,
  "movement_acceleration": 59,
  "movement_sprint_speed": 57,
  "movement_agility": 49,
  "movement_reactions": 80,
  "movement_balance": 49,
  "power_shot_power": 62,
  "power_jumping": 60,
  "power_stamina": 40,
  "power_strength": 70,
  "power_long_shots": 16,
  "mentality_aggression": 37,
  "mentality_interceptions": 13,
  "mentality_positioning": 12,
  "mentality_vision": 66,
  "mentality_penalties": 42,
  "mentality_composure": 60,
  "defending_marking": null,
  "defending_standing_tackle": 20,
  "defending_sliding_tackle": 20,
  "goalkeeping_diving": 85,
  "goalkeeping_handling": 83,
  "goalkeeping_kicking": 82,
  "goalkeeping_positioning": 83,
  "goalkeeping_reflexes": 85,
  "goalkeeping_speed": 58,
  "player_traits": "Solid Player, Leadership, GK Long Throw, Team Player, Comes For Crosses"
}

###
PUT  http://localhost:3003/api/players/161584
Content-Type: application/json

{
  "fifa_update": "2"
}